"""Initial schema

Revision ID: d0bdcd598a7a
Revises: 
Create Date: 2026-03-16 00:01:12.866066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bdcd598a7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bolao', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('competicao_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['codigo_convite'])

    with op.batch_alter_table('competicao', schema=None) as batch_op:
        batch_op.alter_column('disponivel_dashboard',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('regra_pontuacao', schema=None) as batch_op:
        batch_op.alter_column('criador_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('requer_resultado_correto',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('ativar_bonus_gols',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('bonus_placar_perfeito')
        batch_op.drop_column('modo')
        batch_op.drop_column('pontos_placar_exato')
        batch_op.drop_column('pontos_gols_time_casa')
        batch_op.drop_column('pontos_resultado_certo')
        batch_op.drop_column('pontos_gols_time_fora')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('termos_aceitos_em',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('termos_aceitos_em',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('regra_pontuacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pontos_gols_time_fora', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pontos_resultado_certo', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pontos_gols_time_casa', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pontos_placar_exato', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('modo', sa.VARCHAR(length=20), server_default=sa.text("'acertos_parciais'"), nullable=True))
        batch_op.add_column(sa.Column('bonus_placar_perfeito', sa.INTEGER(), nullable=True))
        batch_op.alter_column('ativar_bonus_gols',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('requer_resultado_correto',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('criador_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('competicao', schema=None) as batch_op:
        batch_op.alter_column('disponivel_dashboard',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('bolao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('competicao_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
